### ISSUE TITLE
allowing slashes in querystring

### ISSUE THREAD

**Issue by neo1parekh** [gimox/json-routing#2]
Hi,
Following url Im using 
GET /product/details/:sku_id

in which sku_id can have the "/" forward slash. like GET /product/details/eddd/68-A

I want to consider "edd/68-A" as a string not as a url 
but now this taking as a separate URL. 
can u help me out.
Thanks.

**Comment by gimox** [comment]
Hi
id must not contain "/" characters, so it's very difficult to parse....

I have 2 solution for you.

1) Use query params

routing: `GET /product/details``
browser url:``http://yourserver/product/details?sku_id=edd/68-A``.
In nodejs: req.query.sku_id to get your params

2) Encode in base64 your sku_id. (suggested)
You can use nodejs buffer to do this.

``` js
new Buffer("Hello World").toString('base64'); //SGVsbG8gV29ybGQ=
new Buffer("SGVsbG8gV29ybGQ=", 'base64').toString('ascii')); //Hello World
```

Let me know if this is a solution for you!

**Comment by neo1parekh** [comment]
Thank you for the quick smart solution.
