### ISSUE TITLE
Can I configure multiple directories in routeOptions

### ISSUE THREAD

**Issue by matrixbegins** [gimox/json-routing#3]
I have an application in which I am trying to have modules:
So My idea is each and every module will have a route, policy and controller dir . Once my app initializes I'll read all modules and find routes/policies details and init `routeOptions`
something like:

```
var routeOptions = {
    routesPath      : ['./user/route', '/product/route', '/category/route'],
    controllerPath  : ['./user/controller', '/product/controller', '/category/controller'],
    policyPath      : ['./user/policy', '/product/policy', '/category/policy'],
    cors            : false,
    displayRoute    : true,
    defaultAction   : "index"
}
```

There is a limitation in approach that controller names and policy names can't be same which is ok.
Can you help me to do that?

**Comment by gimox** [comment]
Yes, you can set a custom directory for each ruote. Take a look at global file 

Inside your  myroute.json
<code>
  "GLOBAL": {
    "controllerPath": "./customdir",
    "controller": "test",
    "policyPath":"./lib",
    "policy":["config:setall","config:connection"],
    "baseUrl":"/user"
  }
</code>

**Comment by matrixbegins** [comment]
```
{
  "GLOBAL": {
    "controllerPath": "./customdir",
    "controller": "test",
    "policyPath":"./lib",
    "policy":["config:setall","config:connection"],
    "baseUrl":"/user"
  },
   "/create": {
    "PUT": {
      "route": "index",
      "policy": [
        "auth:check",
        "auth:adduserparams"
      ]
    }
  }
}
```

This is the given file. But how to configure for rest of the modules. It'll be helpful if you can provide a working example with policies. I am new to node js and I used the older version of json-routing in one of my projects.

**Comment by matrixbegins** [comment]
Can implement something like that?

```
// ./app/user/route/user.json
{
  "GLOBAL": {
    "controllerPath": "./user/front",
    "controller": "user",
    "policyPath":"./user/policy",
    "policy":["config:setall","config:connection"],
    "baseUrl":"/user"
  },
   "/login": {
    "GET": {
      "route": "login",
      "policy": []
    },
    "PUT": {
      "route": "loginpost",
      "policy": [
        "auth:check",
      ]
    }
  }
}

// ./app/product/route/product.json
{
  "GLOBAL": {
    "controllerPath": "./product/front",
    "controller": "product",
    "policyPath":"./product/policy",
    "policy":["config:setall","config:connection"],
    "baseUrl":"/user"
  },
   "/create": {
    "PUT": {
      "route": "index",
      "policy": [
        "auth:check",
        "auth:adduserparams"
      ]
    }
  },
  "/product":{
    "GET": {
      "route": "login",
      "policy": []
    }
  }
}
```

However the script that reads all the module and configure `routeOptions` how that will work? can I read all files and merge these json in an array and can pass as `routeOptions`

**Comment by gimox** [comment]
| Can implement something like that?
Yes you can.

the basic structure is only a proposal.
You can change all structure directory and files using " json file Global Options"

if you hasn't policy you can leave it empty 

change this:

```
  "/product":{
    "GET": {
      "route": "login",
      "policy": []
    }
  }

```

in this:

```
  "/product":{
    "GET": {
      "route": "login"
    }
  }
```

about docs:

please read the docs (https://github.com/gimox/json-routing) and take a look at this chapters:
- Change default Options ->for routeOptions
- Change json file Global Options -> for single file config

let me know if there is something that you don't understand

**Comment by gimox** [comment]
ok
