### ISSUE TITLE
Regular Express error 

### ISSUE THREAD

**Issue by pratikindia143** [gimox/json-routing#4]
Hi,

I have been trying to use regular expression.
Basically i have two route which are similar.
1: /testing/:string/:string/:id
2:/testing/:string/:string/:string

I want to manage this two routes using regular express one with integer value and another with string.
"/testing/:string/:string/:/^\d+$": {
    "GET": {
      "route": "test1",
      "policy": [],
      "regex" : true
    }
  },

"/testing/:string/:string/:string": {
    "GET": {
      "route": "test2",
      "policy": []
    }
  },
 but its not working

**Comment by gimox** [comment]
hi this is a trip!
this is same problema as standard express rounting.

the routing see this route as the same.

Try to add a regular expression to the second route:

`/testing/:string/:string/:/^\[a-zA-Z]+$:`

let me know if it work.

**Comment by pratikindia143** [comment]
This is not working i also debug in their actual script. it is considering as single params.
i tried this `/testing/:string/:string/:/^\[a-zA-Z]+$`
it is showing in the registered route as something like this 
`/testing\/:string\/:string\/:/^\[a-zA-Z]+$`
it is adding one extra slash after every params

**Comment by gimox** [comment]
ok added as bug. let me debug some code...

**Comment by gimox** [comment]
resolved in version 2.0
