### ISSUE TITLE
use custom protection route method

### ISSUE THREAD

**Issue by LiorRabin** [gimox/json-routing#6]
Hello,

This project seems really cool and we really want to use it, just have some thoughts about the jwt protection of routes.

Is there a way to customise the protection to use our own middleware?

Regards,
Lior

**Comment by gimox** [comment]
hi,
you can add a middleware called policy look this example:
```
{
"/admin": {
    "GET": {
      "route": "action",
      "policy": [
        "test:check",
        "test:all",
        "./subfolder/test2:index"
      ]
    },
    "POST": {
      "route": "action",
      "policy": [
        "test:all",
      ]
    }
 },
  "/dashboard": {
    "GET": {
      "route": "dashboard",
      }
  }

}
```
route `action` has an array of policy (middleware) you can add here your protection follow express structure.


ps 
you can add a global policy if you need: https://github.com/gimox/json-routing/blob/master/demo/api/routes/globalmdlw.json

**Comment by LiorRabin** [comment]
@gimox thanks for the quick reply.
I'm aware of that solution, just wanted to know if I can override the "protected" functionality :)

**Comment by gimox** [comment]
I'm thinking about something new with pluggable modules..

So the problems are:
- it's not so faster
- need to be compatibility with this version
- require more time
- it must be a very simple

i hope to find a good solution in next months

**Comment by LiorRabin** [comment]
cool :) looking forward for the future

**Comment by gimox** [comment]
yeah!
