### ISSUE TITLE
Pass variables to controller/policy

### ISSUE THREAD

**Issue by LiorRabin** [gimox/json-routing#7]
Hello,
Is there a way to pass variables to controllers and/or middlewares? I don't want to use `global`.
Thanks

**Comment by gimox** [comment]
policy are middleware, you can add an array of routes for every route. It's express!

**Comment by LiorRabin** [comment]
What I meant was how can I pass a variable from other places in my app to one of the controllers for example

**Comment by gimox** [comment]
this is a problem related to nodejs programmig, so you can do something like this:
- use service
- use module
- use event
- use global (very bad)

take a look at google, there are some nice tutorials:
https://www.google.it/search?q=node+js+share+data+between+modules&oq=nodejs+share+data+&aqs=chrome.1.69i57j0l5.9313j0j9&sourceid=chrome&ie=UTF-8

**Comment by LiorRabin** [comment]
Thanks!
